/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as ApiInvitationsSessionRouteImport } from './routes/api/invitations/session'
import { Route as ApiInvitationsLoginRouteImport } from './routes/api/invitations/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsSessionRoute = ApiInvitationsSessionRouteImport.update({
  id: '/api/invitations/session',
  path: '/api/invitations/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsLoginRoute = ApiInvitationsLoginRouteImport.update({
  id: '/api/invitations/login',
  path: '/api/invitations/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitations/login': typeof ApiInvitationsLoginRoute
  '/api/invitations/session': typeof ApiInvitationsSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitations/login': typeof ApiInvitationsLoginRoute
  '/api/invitations/session': typeof ApiInvitationsSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invitations/login': typeof ApiInvitationsLoginRoute
  '/api/invitations/session': typeof ApiInvitationsSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/verify'
    | '/api/auth/$'
    | '/api/invitations/login'
    | '/api/invitations/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/verify'
    | '/api/auth/$'
    | '/api/invitations/login'
    | '/api/invitations/session'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/verify'
    | '/api/auth/$'
    | '/api/invitations/login'
    | '/api/invitations/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInvitationsLoginRoute: typeof ApiInvitationsLoginRoute
  ApiInvitationsSessionRoute: typeof ApiInvitationsSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/session': {
      id: '/api/invitations/session'
      path: '/api/invitations/session'
      fullPath: '/api/invitations/session'
      preLoaderRoute: typeof ApiInvitationsSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/login': {
      id: '/api/invitations/login'
      path: '/api/invitations/login'
      fullPath: '/api/invitations/login'
      preLoaderRoute: typeof ApiInvitationsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInvitationsLoginRoute: ApiInvitationsLoginRoute,
  ApiInvitationsSessionRoute: ApiInvitationsSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
